spring.application.name=proyecto

# DB
spring.datasource.url=jdbc:mysql://db:3306/tickets_db?allowPublicKeyRetrieval=true&useSSL=false
spring.datasource.username=root
spring.datasource.password=root

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# ACTUATOR
management.endpoints.web.exposure.include=health,info

# LOGGING
logging.level.root=INFO
logging.file.name=app.log